### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by robertleeplummerjr** [hardbyte/paillier.js#1]
I see here: https://github.com/hardbyte/paillier.js/blob/master/package.json#L11 it mentions GPL
However here: https://www.npmjs.com/package/homomorphicjs Apache v2

Would you considering clarifying?  Would you consider using a more flexible license, like MIT, for example?

**Comment by hardbyte** [comment]
I might consider changing the license if I work on this further - but most likely it would be a rewrite in something like typescript.

**Comment by robertleeplummerjr** [comment]
The question was: "Which license?"  Can you clarify if it is Apache v2 or GPL?

**Comment by hardbyte** [comment]
Sorry in the commit I changed it so both those links now say Apache 2.0
